language: go

go:
- 1.11.x

env:
    global: 
        - GO111MODULE=on

go_import_path: github.com/robrotheram/gogallery

sudo: false

install: true

before_deploy:
  - PLATFORMS=(linux/386 linux/amd64 linux/arm)

  # build binary for all archs
  - |
    for PLATFORM in "${PLATFORMS[@]}"; do
      echo "Building $PLATFORM"
      GOOS=${PLATFORM%/*}
      GOARCH=${PLATFORM#*/}
      if [ "$GOOS" = "windows" ]; then
        build_cmd="GOOS=$GOOS GOARCH=$GOARCH go build -o gogallery -ldflags '-w -s'"
      else
        build_cmd="CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -o gogallery -ldflags '-d -w -s'"
      fi
      if ! eval $build_cmd; then
        echo "Failed building gogallery for $PLATFORM" && return 1
      fi
      if [ "$GOOS" = "windows" ]; then
        zip gogallery-${GOOS}-${GOARCH}.zip gogallery
      else
        tar cvzf gogallery-${GOOS}-${GOARCH}.tgz gogallery config_sample.yml themes
      fi
    done
  - ls

deploy:
  provider: releases
  api_key: $AUTH_TOKEN
  file:
    - "gogallery-linux-386.tgz"
    - "gogallery-linux-arm.tgz"
    - "gogallery-linux-amd64.tgz"

  skip_cleanup: true
  on:
    tags: true